
FROM golang:1.20 AS builder

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY . ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /centor

FROM envoyproxy/envoy:v1.28.0

COPY --from=builder ./centor /
# Run
ENTRYPOINT ["/centor","--connect","envoy"]